# Generated by Django 5.1.7 on 2026-04-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_setup_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
